name: flutter_todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  share_plus: ^10.1.4
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  flutter_email_sender: ^7.0.0
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  firebase_dynamic_links: ^6.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
